# Generated by Django 3.2.6 on 2021-09-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_your_course_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='your_course',
            old_name='course_id',
            new_name='course',
        ),
    ]
