# Generated by Django 3.2 on 2021-08-13 18:20

import django.core.management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210807_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=django.core.management.utils.get_random_secret_key, max_length=255),
        ),
    ]
