# Generated by Django 3.2.6 on 2021-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, default='http://defaultprofil.com', null=True),
        ),
    ]
